jobs/Models/Profile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace jobs.Models
{
    public class Profile
    {
        public int Id { get; set; }

        [Required]
        public string Picture { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string ShortDescription { get; set; }
        public string PersonalStatement { get; set; }
        public string LookingFor { get; set; }
        public string SkillExpertise { get; set; }
        public string WorkHistory { get; set; }

        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        public ICollection<JobProfile> JobProfiles { get; set; }
    }
}

jobs/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using jobs.Data;
using jobs.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace jobs.Controllers
{
    public class MessagesController : Controller
    {
        ApplicationDbContext _context;

        public MessagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == UserId);

            var messages = _context.Messages.Include(m => m.Job).Include(m=>m.BusinessProfile).Where(m => m.Profile.Id == profile.Id).OrderBy(m=>m.Read).ToList();
           

            return View(messages);
        }

        public IActionResult Details(int id)
        {
            var message = _context.Messages.Include(m=>m.Profile).Include(m=>m.Job).Include(m=>m.BusinessProfile).SingleOrDefault(m => m.Id == id);
            message.Read = true;
            _context.SaveChanges();
            return View(message);
        }


        [HttpPost]
        public IActionResult Send(int id, int jobid)
        {

            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == UserId);
            var businessProfileId = businessProfile.Id;

            var job = _context.Jobs.Single(j => j.Id == jobid);

            var profileId = Int32.Parse(Request.Form["profileId"]);
            var profile = _context.Profiles.SingleOrDefault(p => p.Id == profileId);

            string dateTime = Request.Form["Date"] + " " + Request.Form["Time"] + ":00";

            DateTime parseDateTime = DateTime.Parse(dateTime);

            var message = new Message
            {
                Location = Request.Form["Location"],
                Job = job,
                dateTime = parseDateTime,
                BusinessProfile = businessProfile,
                Profile = profile, 
                CreatedOn = DateTime.Now,
                Read = false
            };

            _context.Messages.Add(message);
            _context.SaveChanges();

            return Content("Did");


        }
    }
}

jobs/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using jobs.Data;
using jobs.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace jobs.Controllers
{
    public class ProfilesController : Controller
    {
        ApplicationDbContext _context;

        public ProfilesController(ApplicationDbContext context)
        {
            
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Applied(int id, int jobId)
        {
            var jpro = _context.JobProfiles.Include(jp=>jp.Profile).Where(jp=>jp.JobId == jobId).ToList();
            var profiles = _context.Profiles.Where(j => j.JobProfiles.All(jp => jp.JobId == 2)).ToList();

            if (jpro.Count > 0)
            {
                ViewData["applicants"] = "loads";
            }
            else {
               
                ViewData["applicants"] = "none";
            }

            var applicants = ViewData["applicants"];

            return View(jpro);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Details(int id, int jobid)
        {
           var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            /*
            string userId = "";

            try
            {
                userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            catch (NullReferenceException ex)
            {
                userId = null;
            }
            */

            var user = _context.Users.Include(u=>u.Profile).SingleOrDefault(u => u.Id == userId);

            if (user.Profile == null)
            {
                ViewBag.admin = true;
                ViewBag.jobid = 0;
            }
            else
            {
                ViewBag.admin = false;
                ViewBag.jobid = jobid;
            }

            var profile = new Profile();

            

            profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == userId);

            
            if (profile == null)
                profile = _context.Profiles.SingleOrDefault(p => p.Id == id);

            if ( profile == null)
                return RedirectToAction("Create");

            /*
            if (userId == id.ToString())
            {
                ViewBag.admin = true;
                ViewBag.jobid = 0;
            }
            else
            {
                ViewBag.admin = false;
                ViewBag.jobid = jobid;
            }
            */
            var loggedInUser = _context.Profiles.SingleOrDefault(p => p.Id == id);

            if (loggedInUser == null)
            {
                ViewData["edit"] = "dont";
            }
            else if (loggedInUser.ApplicationUserId != userId)
            {
                ViewData["edit"] = "edit";
            }

     
            var delete = ViewData["Edit"];

            return View(profile);
        }

        public IActionResult Edit(int id)
        {
            var profile = _context.Profiles.SingleOrDefault(p => p.Id == id);

            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
           

            return View(profile);
        }

        [HttpPost]
        public IActionResult Edit(Profile profile, int id, IFormFile Picture)
        {
            var userprofile = _context.Profiles.SingleOrDefault(p => p.Id == id);
            var fileName = Guid.NewGuid().ToString() + Picture.FileName;

            userprofile.Email = profile.Email;
            userprofile.Facebook = profile.Facebook;
            userprofile.LookingFor = profile.LookingFor;
            userprofile.Name = profile.Name;
            userprofile.PersonalStatement = profile.PersonalStatement;
            userprofile.Phone = profile.Phone;
            userprofile.Picture = fileName;
            userprofile.ShortDescription = profile.ShortDescription;
            userprofile.SkillExpertise = profile.SkillExpertise;
            userprofile.Surname = profile.Surname;
            userprofile.Twitter = profile.Twitter;
            userprofile.Website = profile.Website;
            userprofile.WorkHistory = profile.WorkHistory;

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/propics/", fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                Picture.CopyToAsync(stream);
            }

            _context.SaveChanges();

            return RedirectToAction("Details", new { id = id});
        }

        [HttpPost]
        public IActionResult Create(Profile profile, IFormFile Picture)
        {
            if (!ModelState.IsValid)
            {
                return View(profile);
            }

            var fileName = Guid.NewGuid().ToString() + Picture.FileName;

            var theprofile = new Profile {
                Email = profile.Email,
                Facebook = profile.Facebook,
                LookingFor = profile.LookingFor,
                Name = profile.Name,
                PersonalStatement = profile.PersonalStatement,
                Phone = profile.Phone,
                Picture = fileName,
                ShortDescription = profile.ShortDescription,
                SkillExpertise = profile.SkillExpertise,
                Surname = profile.Surname,
                Twitter = profile.Twitter,
                Website = profile.Website,
                WorkHistory = profile.WorkHistory,
                ApplicationUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value

                
        };

           

            _context.Profiles.Add(theprofile);

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/propics/", fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                Picture.CopyToAsync(stream);
            }

         
             _context.SaveChanges();

            //return  RedirectToAction("Details",theprofile.Id);
            return RedirectToAction("Details", new { id = theprofile.Id });
        }
    }
}

jobs/Views/Profiles/Applied.cshtml
@model IEnumerable<jobs.Models.JobProfile>


@{
    Layout = "~/Views/Shared/_Layout - nosides.cshtml";
    ViewData["Title"] = "Job applicants";
}


<section></section>



<section class="ftco-section ftco-candidates ftco-candidates-2 bg-light">
    <div class="container">

      


        <section class="site-section">
          

            <div class="container">
                @if (ViewData["applicants"] == "none")
                {
                    <h2>You don't have applicants for this job</h2>
                }
                else 
                {
                    <div class="row mb-5">
                        @foreach (var item in Model)
                        {
                           


                            <div class="col-md-6 col-lg-4 mb-5">

                                <div class="card" style="width: 18rem;">
                                    <img src="~/propics/@item.Profile.Picture" class="card-img-top" alt="Card image cap">
                                    <div class="card-body">
                                        <h5 class="card-title">@item.Profile.Name</h5>
                                        <p class="card-text">@item.date.ToLongDateString() </p>
                                        <a href="@Url.Action("Details", new {id = item.Profile.Id, jobid = item.JobId})" class="btn btn-primary">View profile</a>
                                        
                                    </div>
                                </div>
                            </div>


                        }



                    </div>
                    <!--
        <div class="row pagination-wrap mt-5">

            <div class="col-md-12 text-center ">
                <div class="custom-pagination ml-auto">
                    <a href="#" class="prev">Previous</a>
                    <div class="d-inline-block">
                        <a href="#" class="active">1</a>
                        <a href="#">2</a>
                        <a href="#">3</a>
                        <a href="#">4</a>
                    </div>
                    <a href="#" class="next">Next</a>
                </div>
            </div>
        </div>
           -->
                }
            </div>
            
        </section>




    </div>
</section>

jobs/Views/Profiles/Create.cshtml
@model jobs.Models.Profile

@{
    ViewData["Title"] = "Create a profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Enter details</h2>




<section class="site-section">
    <div class="container">
        <div class="row align-items-center mb-5">
        </div>
        <!--- form --->


        @using (Html.BeginForm("Create", "Profiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        <div class="form-group">
            @Html.LabelFor(a => a.Picture)
            @Html.TextBoxFor(a => a.Picture, new { @class = "form-control", type = "file" })
            <p style="color: red">  @Html.ValidationMessageFor(a => a.Picture)</p>
        </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Surname)
                @Html.TextBoxFor(a => a.Surname, new { @class = "form-control" })
                <p style="color: red">  @Html.ValidationMessageFor(a => a.Surname)</p>

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.Name)
                @Html.TextBoxFor(a => a.Name, new { @class = "form-control" })
                <p style="color: red">  @Html.ValidationMessageFor(a => a.Name)</p>

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Email)
                @Html.TextBoxFor(a => a.Email, new { @class = "form-control" })
                <p style="color: red"> @Html.ValidationMessageFor(a => a.Email) </p>
            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Phone)
                @Html.TextBoxFor(a => a.Phone, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Website)
                @Html.TextBoxFor(a => a.Website, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Facebook)
                @Html.TextBoxFor(a => a.Facebook, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Twitter)
                @Html.TextBoxFor(a => a.Twitter, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.ShortDescription)
                @Html.TextBoxFor(a => a.ShortDescription, new { @class = "form-control" })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.PersonalStatement)
                @Html.TextAreaFor(a => a.PersonalStatement, new { @class = "form-control", rows = 3 })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.LookingFor)
                @Html.TextAreaFor(a => a.LookingFor, new { @class = "form-control", rows = 3 })


            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.SkillExpertise)
                @Html.TextAreaFor(a => a.SkillExpertise, new { @class = "form-control", rows = 3 })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.WorkHistory)
                @Html.TextAreaFor(a => a.WorkHistory, new { @class = "form-control", rows = 3 })

            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        }

        <!--- end of form --->



    </div>
</section>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

jobs/Views/Profiles/Details.cshtml
@model jobs.Models.Profile

@{
    ViewData["Title"] = "Profile Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div>

    
    <dl class="dl-horizontal">


        <dt>
            <h2>

                @Html.DisplayFor(model => model.Email)
            </h2>
        </dt>

        <dt>
            <img height="200" width="200" class="img-thumbnail" src="~/propics/@Model.Picture" alt="Italian Trulli">
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>




        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        @if (Model.Website != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Website)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>


        @if (Model.Facebook != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Facebook)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.Facebook)
        </dd>


        @if (Model.Twitter != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Twitter)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.Twitter)
        </dd>


        @if (Model.ShortDescription != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>



        @if (Model.PersonalStatement != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.PersonalStatement)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.PersonalStatement)
        </dd>


        @if (Model.LookingFor != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.LookingFor)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.LookingFor)
        </dd>


        @if (Model.SkillExpertise != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.SkillExpertise)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.SkillExpertise)
        </dd>


        @if (Model.WorkHistory != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.WorkHistory)
            </dt>
        }


        <dd>
            @Html.DisplayFor(model => model.WorkHistory)
        </dd>

     
        @if (ViewData["Edit"].ToString() == "dont")
        {
            <a href="@Url.Action("Edit", "Profiles", new {id= Model.Id})" , class="btn btn-primary btn-lg">Edit</a>
        }
        else if (ViewData["Edit"].ToString() == "edit")
        {
           
        }


    </dl>
</div>
<div>
    @if (ViewBag.admin == true)
    {
        <div class="col-md-6">
            <div class="team d-md-flex">
                <div class="text pl-md-4">
                    <p>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#form">
                            Send appointment
                        </button>
                    </p>
                </div>
            </div>
        </div>
    }

    <div class="modal fade" id="form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <h5 class="modal-title" id="exampleModalLabel">Send appointment</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>




                @using (Html.BeginForm("Send", "Messages", new { id = Model.Id, jobid = ViewBag.jobid }, FormMethod.Post))
                {
                    <div class="modal-body">


                        <input type="hidden" name="jobId" value="@ViewBag.jobId" />

                        <div class="form-group">
                            <label for="Location">Location</label>
                            <input class="form-control" name="Location" id="Location" />
                        </div>


                        <div class="form-group">
                            <label for="Date">Date</label>
                            <input class="form-control" name="Date" type="date" />
                        </div>

                        <div class="form-group">
                            <label for="Time">Time</label>
                            <input type="time" class="form-control" name="Time" />
                        </div>

                    </div>
                    <div class="modal-footer border-top-0 d-flex justify-content-center">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>

                }
            </div>
        </div>
    </div>

</div>

jobs/Views/Profiles/Edit.cshtml
@model jobs.Models.Profile

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Profile</h4>
<hr />
<div class="row">
    <div class="col-md">
        @using (Html.BeginForm("Edit", "Profiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                @Html.LabelFor(a => a.Picture)
                @Html.TextBoxFor(a => a.Picture, new { @class = "form-control", type = "file" })
                <div style="color: red">
                    @Html.ValidationMessageFor(a => a.Picture)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Surname)
                @Html.TextBoxFor(a => a.Surname, new { @class = "form-control" })
                <div style="color: red">
                    @Html.ValidationMessageFor(a => a.Surname)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.Name)
                @Html.TextBoxFor(a => a.Name, new { @class = "form-control" })
                <div style="color: red">
                    @Html.ValidationMessageFor(a => a.Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Email)
                @Html.TextBoxFor(a => a.Email, new { @class = "form-control" })
                <div style="color: red">
                    @Html.ValidationMessageFor(a => a.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Phone)
                @Html.TextBoxFor(a => a.Phone, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Website)
                @Html.TextBoxFor(a => a.Website, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Facebook)
                @Html.TextBoxFor(a => a.Facebook, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.Twitter)
                @Html.TextBoxFor(a => a.Twitter, new { @class = "form-control" })

            </div>

            <div class="form-group">
                @Html.LabelFor(a => a.ShortDescription)
                @Html.TextBoxFor(a => a.ShortDescription, new { @class = "form-control" })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.PersonalStatement)
                @Html.TextAreaFor(a => a.PersonalStatement, new { @class = "form-control", rows = 3 })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.LookingFor)
                @Html.TextAreaFor(a => a.LookingFor, new { @class = "form-control", rows = 3 })


            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.SkillExpertise)
                @Html.TextAreaFor(a => a.SkillExpertise, new { @class = "form-control", rows = 3 })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.WorkHistory)
                @Html.TextAreaFor(a => a.WorkHistory, new { @class = "form-control", rows = 3 })

            </div>

         
                <button type="submit" class="btn btn-primary">Submit</button>
           

        }
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

jobs/Views/Profiles/View.cshtml
@model IEnumerable<jobs.Models.JobProfile>


@{
    Layout = "~/Views/Shared/_Layout - nosides.cshtml";
}


<section>

    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#form">
        See Modal with Form
    </button>


    <div class="modal fade" id="form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <h5 class="modal-title" id="exampleModalLabel">Create Account</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="email1">Email address</label>
                            <input type="email" class="form-control" id="email1" aria-describedby="emailHelp" placeholder="Enter email">
                            <small id="emailHelp" class="form-text text-muted">Your information is safe with us.</small>
                        </div>
                        <div class="form-group">
                            <label for="password1">Password</label>
                            <input type="password" class="form-control" id="password1" placeholder="Password">
                        </div>
                        <div class="form-group">
                            <label for="password1">Confirm Password</label>
                            <input type="password" class="form-control" id="password2" placeholder="Confirm Password">
                        </div>
                    </div>
                    <div class="modal-footer border-top-0 d-flex justify-content-center">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>



<section class="ftco-section ftco-candidates ftco-candidates-2 bg-light">
    <div class="container">
        <div class="row">

            @foreach (var item in Model)
            {
                <div class="col-md-6">
                    <div class="team d-md-flex">


                        <a href="@Url.Action("Details", new {id = item.Profile.Id })">
                            <div class="img"> <img height="200" width="200" class="rounded-circle" src="~/propics/@item.Profile.Picture" alt="Italian Trulli"></div>
                        </a>
                        <div class="text pl-md-4">
                            <span class="location mb-0">@item.Profile.Twitter</span>
                            <h2>@item.Profile.Name</h2>
                            <span class="position">@item.Profile.PersonalStatement</span>
                            <p>@item.Profile.PersonalStatement</p>
                            <span class="seen">Last Activity 4 months ago</span>


                            <p>
                                                               @Html.ActionLink("Shortlist", "Send", "Messages", new { profileId = item.Profile.Id, jobId = ViewBag.jobId }, new { @class = "btn btn-primary" })
                            </p>
                        </div>



                    </div>
                </div>
            }




        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>