jobs/Controllers/InboxesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using jobs.Data;
using jobs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace jobs.Controllers
{
    public class InboxesController : Controller
    {
        ApplicationDbContext _context;

        public InboxesController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: Inboxes/Details/5
        public ActionResult Details(int id)
        {

            return View(_context.Inboxes.Where(i => i.Id ==id).Single());
        }

        // GET: Inboxes/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        public ActionResult Index()
        {

            return View(_context.Inboxes.ToList());
        }

        // POST: Inboxes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Inbox inbox)
        {
            if (!ModelState.IsValid)
            {

                return View(inbox);
            }

            _context.Inboxes.Add(inbox);
            _context.SaveChanges();

            Response.Cookies.Append("content", "content");

            return RedirectToAction("Index", "Jobs");//, new { msgSent = "woza wena" });
                       
        }

        // GET: Inboxes/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Inboxes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return Content("sasa");
            }
            catch
            {
                return View();
            }
        }

        // GET: Inboxes/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Inboxes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return Content("halala");
            }
            catch
            {
                return View();
            }
        }
    }
}

jobs/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using jobs.Data;
using jobs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace jobs.Controllers
{
    public class JobsController : Controller
    {
        //private readonly UserManager<ApplicationUser> _userManager;

        ApplicationDbContext _context;

        

        public JobsController(ApplicationDbContext context)
        {
           
            _context = context;
        }

        [Authorize]
        public IActionResult Apply(int id)
        {

           

            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
         


            var profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == UserId);

            if (profile == null)
            {
                return RedirectToAction("Create", "Profiles");
            }
            else
            {
                var appliedJob = new JobProfile
                {
                    JobId = id,
                    ProfileId = profile.Id,
                    date = DateTime.Now
                };

                _context.JobProfiles.Add(appliedJob);
                _context.SaveChanges();
            }

            var job = _context.Jobs.Include(j=>j.businessProfile).SingleOrDefault(j => j.Id == id);

            ViewBag.Applied = "true";
            ViewBag.application = true;

            return View("Details", job);
        }

        public IActionResult PostedJobs()
        {
            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == UserId);

            if (businessProfile == null)
                return RedirectToAction("Create", "BusinessProfile");

            var jobs = _context.Jobs.Include(j => j.JobProfiles).Include(j => j.businessProfile).Where(j => j.businessProfile == businessProfile).ToList();

            if (jobs == null)
                ViewBag.jobs = false;
            else
                ViewBag.jobs = true;

            return View(jobs);
        }

        // POST: Inboxes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Send(Inbox inbox)
        {
            if (!ModelState.IsValid)
            {

                return View(inbox);
            }

            _context.Inboxes.Add(inbox);
            _context.SaveChanges();

            TempData["sasa"]= 23;
            ViewData["sasa"] = 23;

            return View("Index", _context.Jobs.Include(j => j.businessProfile).Where(j => j.Available == true).ToList());
            // return RedirectToAction("Index");

        }

        public IActionResult Index()
        {
           
            

           return View(_context.Jobs.Include(j => j.businessProfile).Where(j => j.Available == true).ToList());
        }

        //[Authorize(Roles ="Administrator")]
        public IActionResult Create()
        {
            
            //asdf
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            
                
           // return Content(User.Identity.Name);



            
            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == UserId);

            if (businessProfile == null)
                return RedirectToAction("Create", "BusinessProfile");

         


            return View();
            
        }

        public IActionResult Applied()
        {
            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == UserId);



            var jobprofiles = _context.JobProfiles.Include(jp => jp.Job.businessProfile).Where(jp => jp.Profile == profile);

            ViewData["numberOfJobs"] = jobprofiles.Count();

            if (profile == null)
                return RedirectToAction("Create", "Profiles");

            if (jobprofiles == null)
                ViewBag.jobs = false;
            else
                ViewBag.jobs = true;

            return View("AppliedJobs", jobprofiles);
        }

        [HttpPost]
        public IActionResult Create(Job job)
        {

            if (!ModelState.IsValid)
            {

                return View(job);
            }
            else
            {
                var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == UserId);

                

                job.PostDate = DateTime.Now;

                switch (job.Type)
                {
                    case "Full time":
                        job.badge = "badge-warning";
                        break;

                    case "Part time":
                        job.badge = "badge-success";
                        break;

                    case "Freelance":
                        job.badge = "badge-primary";
                        break;

                    case "Internship":
                        job.badge = "badge-info";
                        break;

                    case "Temporary":
                        job.badge = "badge-dark";
                        break;
                }

                job.businessProfile = businessProfile;
                _context.Jobs.Add(job);
                _context.SaveChanges();

                return RedirectToAction("PostedJobs");
            }
        }

        public IActionResult Details(int id)
        {
            var job = _context.Jobs.Include(j=>j.businessProfile).SingleOrDefault(j => j.Id == id);
            string userId = "";

            try
            {
                userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            catch (NullReferenceException ex)
            {
                userId = null;
            }

            if (userId == null)
            {
                ViewBag.Applied = "false";
                return View(job);
            }

            var user = _context.Users.SingleOrDefault(u => u.Id == userId);

            var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == userId);

            


            if (user.Position == "Employer" && job.businessProfile.ApplicationUserId == userId)
            {
                ViewBag.Applied = "owner";
            }
            else if (businessProfile != null)
            {
                ViewBag.Applied = "admin";
            }
            else if (user.Position == "Employer" && businessProfile == null)
            {
                ViewBag.Applied = "admin";
            }
            else
            {
                var profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == userId);

                if (profile != null)
                {
                    var appliedJob = _context.JobProfiles.Where(jp => jp.ProfileId == profile.Id && jp.JobId == id).ToList();

                    if (appliedJob.Count == 0)
                    {
                        ViewBag.Applied = "false";
                    }
                    else
                    {
                        ViewBag.Applied = "true";
                    }
                }
                else
                {
                    ViewBag.Applied = "false";
                }

            }

            return View(job);
        }

        public IActionResult Edit(int id)
        {
            return View(_context.Jobs.SingleOrDefault(j => j.Id == id));
        }

        public IActionResult Search()
        {
            var province = Request.Form["Province"];
            var jobtype = Request.Form["JobType"];
            var title = Request.Form["Title"];

            
            List<Job> jobs = new List<Job>();

            if (title != String.Empty && province == string.Empty && jobtype == string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            else if (title != String.Empty && jobtype == string.Empty && province != string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase) && j.Location == province).ToList();
            }
            else if (title != String.Empty && jobtype != string.Empty && province == string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase) && j.Type == jobtype).ToList();
            }
            else if (title != String.Empty && jobtype != string.Empty && province != string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase) && j.Type == jobtype && j.Location == province).ToList();
            }
            else if (title == String.Empty && jobtype != string.Empty && province != string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j=>j.Type == jobtype && j.Location == province).ToList();
            }
            else if (title == String.Empty && jobtype != string.Empty && province == string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Type == jobtype).ToList();
            }
            else if (title == String.Empty && jobtype == string.Empty && province != string.Empty)
            {

jobs/Views/Shared/_Layout - nosides.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Jobs</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="~/css/custom-bs.css">
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/fonts/line-icons/style.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/mphoza.css">
</head>
<body id="top">

    <div class="site-wrap">
        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div> <!-- .site-mobile-menu -->
        <!-- NAVBAR -->
        <header class="site-navbar mt-3">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="site-logo col-6">@Html.ActionLink("CAREERS", "Index", "Jobs")</div>
                    <nav class="mx-auto site-navigation">
                        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0" style="list-style-type: none;">
                            <partial name="_Menu" />
                        </ul>
                    </nav>
                    <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                        <div class="ml-auto">
                           
                            <a href="@Url.Action( "Create","Inboxes")" class="btn btn-primary border-width-2 d-none d-lg-inline-block">
                                <span class="mr-2 icon-paper-plane"></span>Contact Us
                            </a>
                        </div>
                        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3">
                            <span class="icon-menu h3 m-0 p-0 mt-2"></span>
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <!-- HOME -->
        <section class="home-section section-hero inner-page overlay bg-image" style="background-image: url('../../../images/hero_1.jpg' );"
                 id="home-section">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-12">
                        <div class="mb-5 text-center">
                            <h1 class="text-white font-weight-bold">

                                @ViewData["Title"]

                            </h1>
                            <p>Find your dream jobs in our powerful career website.</p>
                        </div>
                    </div>
                </div>
            </div>

        </section>


        <div class="ftco-section bg-light">
            <div class="container" style="padding-top: 50px">



                <div class="row">

                    <div class="col-md-12 col-lg-12 mb-5 bg-white">


                         @RenderBody()
                        


                    </div>

                </div>
            </div>
        </div>

        <section class="site-section py-4 mb-5 border-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12 text-center mt-4 mb-5">
                        <div class="row justify-content-center">
                            <div class="col-md-7">
                                <h2 class="section-title mb-2">Our Candidates Work In Company</h2>
                                <p class="lead">
                                    Porro error reiciendis commodi beatae omnis similique voluptate rerum ipsam fugit
                                    mollitia ipsum facilis expedita tempora suscipit iste
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-lg-3 col-md-6 text-center">
                        <img src="../../../images/logo_mailchimp.svg" alt="Image" class="img-fluid logo-1">
                    </div>
                    <div class="col-6 col-lg-3 col-md-6 text-center">
                        <img src="../../../images/logo_paypal.svg" alt="Image" class="img-fluid logo-2">
                    </div>
                    <div class="../../../col-6 col-lg-3 col-md-6 text-center">
                        <img src="images/logo_stripe.svg" alt="Image" class="img-fluid logo-3">
                    </div>
                    <div class="col-6 col-lg-3 col-md-6 text-center">
                        <img src="../../../images/logo_visa.svg" alt="Image" class="img-fluid logo-4">
                    </div>
                </div>
            </div>
        </section>

        <section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('images/hero_1.jpg');">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <h2 class="text-white">Looking For A Job?</h2>
                        <p class="mb-0 text-white lead">
                            Lorem ipsum dolor sit amet consectetur adipisicing elit tempora adipisci
                            impedit.
                        </p>
                    </div>
                    <div class="col-md-3 ml-auto">
                        <a href="@Url.Action("Register", "Identity/Account" )" class="btn btn-warning btn-block btn-lg">Sign Up</a>
                    </div>
                </div>
            </div>
        </section>


        <footer class="site-footer">

            <div class="container">
                <div class="row mb-5">
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Search Trending</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Web Design</a></li>
                            <li><a href="#">Graphic Design</a></li>
                            <li><a href="#">Web Developers</a></li>
                            <li><a href="#">Python</a></li>
                            <li><a href="#">HTML5</a></li>
                            <li><a href="#">CSS3</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Company</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Career</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Resources</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Support</h3>
                        <ul class="list-unstyled">
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Terms of Service</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Contact Us</h3>
                        <div class="footer-social">
                            <a href="#"><span class="icon-facebook"></span></a>
                            <a href="#"><span class="icon-twitter"></span></a>
                            <a href="#"><span class="icon-instagram"></span></a>
                            <a href="#"><span class="icon-linkedin"></span></a>
                        </div>
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-12">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                            with <i class="icon-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
                                                                                       target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <!-- SCRIPTS -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/isotope.pkgd.min.js"></script>
    <script src="~/js/stickyfill.min.js"></script>
    <script src="~/js/jquery.fancybox.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>

    <script src="~/js/custom.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

jobs/Views/Shared/_Menu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<li>@Html.ActionLink("Home","Index", "Jobs")</li>
<li>@Html.ActionLink("Job Listings", "Index", "Jobs")</li>




<li> <partial name="_LoginPartial" /> </li>

<li class="d-lg-none"><a href="contact.html">Contact Us</a></li>