jobs/Models/BusinessProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace jobs.Models
{
    public class BusinessProfile
    {
        public int Id { get; set; }
        [Display(Name ="Company name")]
        [Required]
        public string Name { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Industry { get; set; }
        [Required]
        public string Province { get; set; }
        [Required]
        public string Website { get; set; }

        

        public string ApplicationUserId { get; set; }
        public ApplicationUser applicationUser { get; set; }
    }
}

jobs/Controllers/BusinessProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using jobs.Data;
using jobs.Models;
using Microsoft.AspNetCore.Mvc;

namespace jobs.Controllers
{
    public class BusinessProfileController : Controller
    {
        ApplicationDbContext _context;

        public BusinessProfileController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Single()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var profile = _context.BusinessProfiles.Where(b=>b.ApplicationUserId == userId).Single();
            return View(profile);
        }

        public IActionResult Edit(int id)
        {
            var profile = _context.BusinessProfiles.SingleOrDefault(b => b.Id == id);
            return View(profile);
        }

        [HttpPost]
        public IActionResult Edit(BusinessProfile profile, int id)
        {
            var userprofile = _context.BusinessProfiles.SingleOrDefault(p => p.Id == id);

            userprofile.Industry = profile.Industry;
            userprofile.Name = profile.Name;
            userprofile.Phone = profile.Phone;
            userprofile.Province = profile.Province;
            userprofile.Website = profile.Website;
            userprofile.ApplicationUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            _context.SaveChanges();

            return RedirectToAction("Single", new {id = id });
        }

        public IActionResult Create()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewBag.UserId = userId;
            return View();
        }

        [HttpPost]
        public IActionResult Create(BusinessProfile businessProfile)
        {
            if (!ModelState.IsValid)
            {
                return View(businessProfile);
            }
            else
            {
                var applicationUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                businessProfile.ApplicationUserId = applicationUserId;

                _context.BusinessProfiles.Add(businessProfile);
                _context.SaveChanges();

                return RedirectToAction("Create", "Jobs");

                
            }


            
        }
    }
}

jobs/Views/BusinessProfile/Create.cshtml
@model jobs.Models.BusinessProfile

@{
    ViewData["Title"] = "Create a business profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h4>BusinessProfile</h4>
<hr />
<div class="row">
    <div class="col-md">
        @using (Html.BeginForm("Create"))
        {



            @Html.HiddenFor(a => a.ApplicationUserId, new { Value = ViewBag.UserId })
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @Html.LabelFor(a => a.Name)
                @Html.TextBoxFor(a => a.Name, new { @class = "form-control", placeholder = "O O Oros" })
                @Html.ValidationMessageFor(a => a.Name, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.Phone)
                @Html.TextBoxFor(a => a.Phone, new { @class = "form-control", placeholder = "e.g. 011 880 0992" })
                @Html.ValidationMessageFor(a => a.Phone, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.Industry)
                @Html.DropDownListFor(x => x.Industry, new List<SelectListItem>
                {
                     new SelectListItem() {Text = "ICT", Value="ICT"},
                     new SelectListItem() {Text = "Finance", Value="Finance"},
                     new SelectListItem() {Text = "Sales", Value="Sales"},
                     new SelectListItem() {Text = "Engineering", Value="Engineering"},
                     new SelectListItem() {Text = "General", Value="General"}
                }, new {@class="form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.Province)
                @Html.DropDownListFor(x => x.Province, new List<SelectListItem>
                {
                      new SelectListItem() {Text = "Western Cape", Value="Western Cape"},
                      new SelectListItem() {Text = "Eastern Cape", Value="Eastern Cape"},
                      new SelectListItem() {Text = "Northern Cape", Value="Northern Cape"},
                      new SelectListItem() {Text = "North West", Value="North West"},
                      new SelectListItem() {Text = "Freestate", Value="Freestate"},
                      new SelectListItem() {Text = "Kwazulu Natal", Value="Kwazulu Natal"},
                      new SelectListItem() {Text = "Gauteng", Value="Gauteng"},
                      new SelectListItem() {Text = "Limpopo", Value="Limpopo"},
                      new SelectListItem() {Text = "Mpumalanga", Value="Mpumalanga"}
                }, new {@class="form-control" })

            </div>
            <div class="form-group">
                @Html.LabelFor(a => a.Website)
                @Html.TextBoxFor(a => a.Website, new { @class = "form-control", placeholder = "O O Oros" })
                @Html.ValidationMessageFor(a => a.Website, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        }
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

jobs/Views/BusinessProfile/Edit.cshtml
@model jobs.Models.BusinessProfile

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h4>Edit Business Profile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
            @using (Html.BeginForm("Edit"))
            {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    @Html.HiddenFor(b=>b.Id)

                    @Html.LabelFor(b=>b.Name)
                    @Html.TextBoxFor(b=>b.Name)
                    
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(b => b.Phone)
                    @Html.TextBoxFor(b => b.Phone)
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(b => b.Industry)
                    @Html.DropDownListFor(x => x.Industry, new List<SelectListItem>
                   {
                        new SelectListItem() {Text = "ICT", Value="ICT"},
                        new SelectListItem() {Text = "Finance", Value="Finance"},
                        new SelectListItem() {Text = "Sales", Value="Sales"},
                        new SelectListItem() {Text = "Engineering", Value="Engineering"},
                        new SelectListItem() {Text = "General", Value="General"}
                   }, new {@class="form-control" })
                    <span asp-validation-for="Industry" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(b => b.Province)
                    @Html.DropDownListFor(x => x.Province, new List<SelectListItem>
                    {
                          new SelectListItem() {Text = "Western Cape", Value="Western Cape"},
                          new SelectListItem() {Text = "Eastern Cape", Value="Eastern Cape"},
                          new SelectListItem() {Text = "Northern Cape", Value="Northern Cape"},
                          new SelectListItem() {Text = "North West", Value="North West"},
                          new SelectListItem() {Text = "Freestate", Value="Freestate"},
                          new SelectListItem() {Text = "Kwazulu Natal", Value="Kwazulu Natal"},
                          new SelectListItem() {Text = "Gauteng", Value="Gauteng"},
                          new SelectListItem() {Text = "Limpopo", Value="Limpopo"},
                          new SelectListItem() {Text = "Mpumalanga", Value="Mpumalanga"}
                    }, new {@class="form-control" })
                    <span asp-validation-for="Province" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(b => b.Website)
                    @Html.TextBoxFor(b => b.Website)
                    <span asp-validation-for="Website" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            }
       
    </div>
</div>

<div>
    @Html.ActionLink("Back", "Single", "BusinessProfile")
   
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

jobs/Views/BusinessProfile/Single.cshtml
@model jobs.Models.BusinessProfile

<div>
    <h4>Business Profile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Industry)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Industry)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Province)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Province)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
</div>