jobs/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace jobs.Models
{
    public class Job
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Type { get; set; }

        [Required]
        public string Description { get; set; }
        public DateTime PostDate { get; set; }

        
        [Display(Name = "Expiry date")]
        [Required(ErrorMessage = "Expiry date is required")]
        public DateTime ExpiryDate { get; set; }

        [Required]
        public string Location { get; set; }
        [Display(Name ="Years of experience")]
        public string ExperienceYears { get; set; }
        [Display(Name = "Salary range")]
        public string SalaryRange { get; set; }

        
        public string Responsibilities { get; set; }

        [Display(Name = "Education and Qualifications")]
        public string EducationExperience { get; set; }
        public string Benefits { get; set; }
        public string badge { get; set; }
        public bool Available { get; set; }

        public ICollection<JobProfile> JobProfiles { get; set; }

        public BusinessProfile businessProfile { get; set; }
    }
}

jobs/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using jobs.Data;
using jobs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace jobs.Controllers
{
    public class JobsController : Controller
    {
        //private readonly UserManager<ApplicationUser> _userManager;

        ApplicationDbContext _context;

        

        public JobsController(ApplicationDbContext context)
        {
           
            _context = context;
        }

        [Authorize]
        public IActionResult Apply(int id)
        {

           

            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
         


            var profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == UserId);

            if (profile == null)
            {
                return RedirectToAction("Create", "Profiles");
            }
            else
            {
                var appliedJob = new JobProfile
                {
                    JobId = id,
                    ProfileId = profile.Id,
                    date = DateTime.Now
                };

                _context.JobProfiles.Add(appliedJob);
                _context.SaveChanges();
            }

            var job = _context.Jobs.Include(j=>j.businessProfile).SingleOrDefault(j => j.Id == id);

            ViewBag.Applied = "true";
            ViewBag.application = true;

            return View("Details", job);
        }

        public IActionResult PostedJobs()
        {
            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == UserId);

            if (businessProfile == null)
                return RedirectToAction("Create", "BusinessProfile");

            var jobs = _context.Jobs.Include(j => j.JobProfiles).Include(j => j.businessProfile).Where(j => j.businessProfile == businessProfile).ToList();

            if (jobs == null)
                ViewBag.jobs = false;
            else
                ViewBag.jobs = true;

            return View(jobs);
        }

        // POST: Inboxes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Send(Inbox inbox)
        {
            if (!ModelState.IsValid)
            {

                return View(inbox);
            }

            _context.Inboxes.Add(inbox);
            _context.SaveChanges();

            TempData["sasa"]= 23;
            ViewData["sasa"] = 23;

            return View("Index", _context.Jobs.Include(j => j.businessProfile).Where(j => j.Available == true).ToList());
            // return RedirectToAction("Index");

        }

        public IActionResult Index()
        {
           
            

           return View(_context.Jobs.Include(j => j.businessProfile).Where(j => j.Available == true).ToList());
        }

        //[Authorize(Roles ="Administrator")]
        public IActionResult Create()
        {
            
            //asdf
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            
                
           // return Content(User.Identity.Name);



            
            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == UserId);

            if (businessProfile == null)
                return RedirectToAction("Create", "BusinessProfile");

         


            return View();
            
        }

        public IActionResult Applied()
        {
            var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == UserId);



            var jobprofiles = _context.JobProfiles.Include(jp => jp.Job.businessProfile).Where(jp => jp.Profile == profile);

            ViewData["numberOfJobs"] = jobprofiles.Count();

            if (profile == null)
                return RedirectToAction("Create", "Profiles");

            if (jobprofiles == null)
                ViewBag.jobs = false;
            else
                ViewBag.jobs = true;

            return View("AppliedJobs", jobprofiles);
        }

        [HttpPost]
        public IActionResult Create(Job job)
        {

            if (!ModelState.IsValid)
            {

                return View(job);
            }
            else
            {
                var UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == UserId);

                

                job.PostDate = DateTime.Now;

                switch (job.Type)
                {
                    case "Full time":
                        job.badge = "badge-warning";
                        break;

                    case "Part time":
                        job.badge = "badge-success";
                        break;

                    case "Freelance":
                        job.badge = "badge-primary";
                        break;

                    case "Internship":
                        job.badge = "badge-info";
                        break;

                    case "Temporary":
                        job.badge = "badge-dark";
                        break;
                }

                job.businessProfile = businessProfile;
                _context.Jobs.Add(job);
                _context.SaveChanges();

                return RedirectToAction("PostedJobs");
            }
        }

        public IActionResult Details(int id)
        {
            var job = _context.Jobs.Include(j=>j.businessProfile).SingleOrDefault(j => j.Id == id);
            string userId = "";

            try
            {
                userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            catch (NullReferenceException ex)
            {
                userId = null;
            }

            if (userId == null)
            {
                ViewBag.Applied = "false";
                return View(job);
            }

            var user = _context.Users.SingleOrDefault(u => u.Id == userId);

            var businessProfile = _context.BusinessProfiles.SingleOrDefault(bp => bp.ApplicationUserId == userId);

            


            if (user.Position == "Employer" && job.businessProfile.ApplicationUserId == userId)
            {
                ViewBag.Applied = "owner";
            }
            else if (businessProfile != null)
            {
                ViewBag.Applied = "admin";
            }
            else if (user.Position == "Employer" && businessProfile == null)
            {
                ViewBag.Applied = "admin";
            }
            else
            {
                var profile = _context.Profiles.SingleOrDefault(p => p.ApplicationUserId == userId);

                if (profile != null)
                {
                    var appliedJob = _context.JobProfiles.Where(jp => jp.ProfileId == profile.Id && jp.JobId == id).ToList();

                    if (appliedJob.Count == 0)
                    {
                        ViewBag.Applied = "false";
                    }
                    else
                    {
                        ViewBag.Applied = "true";
                    }
                }
                else
                {
                    ViewBag.Applied = "false";
                }

            }

            return View(job);
        }

        public IActionResult Edit(int id)
        {
            return View(_context.Jobs.SingleOrDefault(j => j.Id == id));
        }

        public IActionResult Search()
        {
            var province = Request.Form["Province"];
            var jobtype = Request.Form["JobType"];
            var title = Request.Form["Title"];

            
            List<Job> jobs = new List<Job>();

            if (title != String.Empty && province == string.Empty && jobtype == string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            else if (title != String.Empty && jobtype == string.Empty && province != string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase) && j.Location == province).ToList();
            }
            else if (title != String.Empty && jobtype != string.Empty && province == string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase) && j.Type == jobtype).ToList();
            }
            else if (title != String.Empty && jobtype != string.Empty && province != string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Title.Contains(title, StringComparison.OrdinalIgnoreCase) && j.Type == jobtype && j.Location == province).ToList();
            }
            else if (title == String.Empty && jobtype != string.Empty && province != string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j=>j.Type == jobtype && j.Location == province).ToList();
            }
            else if (title == String.Empty && jobtype != string.Empty && province == string.Empty)
            {
                jobs = _context.Jobs.Include(j => j.businessProfile).Where(j => j.Type == jobtype).ToList();
            }
            else if (title == String.Empty && jobtype == string.Empty && province != string.Empty)
            {

jobs/Views/Jobs/AppliedJobs.cshtml
@model IEnumerable<jobs.Models.JobProfile>

@{
    ViewData["Title"] = "Jobs applied for";
    Layout = "~/Views/Shared/_Layout - nosides.cshtml";
}


<section class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="section-title mb-2">@ViewData["numberOfJobs"] Applied Jobs</h2>
            </div>
        </div>

        @if (ViewBag.jobs)
        {
            <div class="mb-5">
                @foreach (var item in Model)
                {
                    <div class="row border-bottom job-item">
                        <div class="col-sm">
                            <span class="badge badge-primary px-2 py-1 mb-3"> @Html.DisplayFor(modelItem => item.Job.Type)</span>
                            <h2> @Html.ActionLink(item.Job.Title, "Details", "Jobs", new { id = item.Job.Id })</h2>
                            <p class="meta">Publisher: <strong>@item.Job.businessProfile.Name</strong> </p>
                        </div>
                        <div class="col-sm text-center">
                            <h3> @Html.DisplayFor(modelItem => item.Job.Location)</h3>

                        </div>
                        <div class="col-sm text-md-right">
                            <strong class="text-black">  @Html.DisplayFor(modelItem => item.Job.SalaryRange)</strong>
                        </div>
                    </div>
                }

            </div>
        }
        else
        {
            <div class="mb-5">
                <p>nigga you have no jobs</p>

            </div>


        }
    </div>

    <!--
    <div class="row pagination-wrap">
        <div class="col-md-6 text-center text-md-left">
            <div class="custom-pagination ml-auto">
                <a href="#" class="prev">Previous</a>
                <div class="d-inline-block">
                    <a href="#" class="active">1</a>
                    <a href="#">2</a>
                    <a href="#">3</a>
                    <a href="#">4</a>
                </div>
                <a href="#" class="next">Next</a>
            </div>
        </div>
    </div>
        -->

</section>

jobs/Views/Jobs/Details.cshtml
@model jobs.Models.Job

@{
    Layout = "~/Views/Shared/_Layout - nosides.cshtml";
    ViewData["Title"] = "Job Details";
}

<!DOCTYPE html>

<section class="site-section">
    <div class="container">
        <div class="row align-items-center mb-5">
            <div class="col-lg-8 mb-4 mb-lg-0">
                <div class="d-flex align-items-center">

                    <div>
                        <h2>@Model.Title</h2>
                        <div>
                            <span class="m-2"><span class="icon-room mr-2"></span> @Model.businessProfile.Name</span>
                            <span class="m-2"><span class="icon-room mr-2"></span>@Model.Location</span>
                            <span class="m-2">
                                <span class="icon-clock-o mr-2"></span><span class="text-primary">
                                    @Model.Type
                                </span>
                            </span>
                        </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="row">

                    <div class="col-6">
                        @if (ViewBag.Applied == "true")
                        {
                        <button type="button" class="btn btn-primary" disabled>You've applied</button>
                        }
                        else if (ViewBag.Applied == "false")
                        {
                            using (Html.BeginForm("Apply", "Jobs", new { id = Model.Id }))
                            {
                                <input type="submit" value="Apply Now" class="btn btn-primary  py-2 px-5">

                            }
                        }
                        else
                        {

                        }

                    </div>
                </div>
            </div>
        </div>

        @if (ViewBag.application == true)
        {
            <div class="alert alert-primary" role="alert">
                Thank you for applying, please keep checking your mail
            </div>
        }

        <div class="row">




            <div class="col-lg-8">



                <div class="mb-5">
                    <h3 class="h5 d-flex align-items-center mb-4 text-primary">
                        <span class="icon-align-left mr-3"></span>Job Description
                    </h3>
                    <p>
                        @Model.Description
                    </p>

                </div>

                @if (Model.Responsibilities != null)
                {
                    <div class="mb-5">
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary">
                            <span class="icon-rocket mr-3"></span>Responsibilities
                        </h3>
                        @Model.Responsibilities
                    </div>
                }

                @if (Model.EducationExperience != null)
                {
                    <div class="mb-5">
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary">
                            <span class="icon-book mr-3"></span>Education +
                            Experience
                        </h3>
                        @Model.EducationExperience
                    </div>
                }

                @if (Model.Benefits != null)
                {
                    <div class="mb-5">
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary">
                            <span class="icon-turned_in mr-3"></span>Other
                            Benifits
                        </h3>
                        @Model.Benefits
                    </div>
                }

                <div>
                    @if (ViewBag.Applied == "owner")
                    {
                        <span class="ml-0 mr-2 mb-2">
                            <span class="icon-briefcase mr-2"></span>
                            @Html.ActionLink("Edit", "Edit", "Jobs", new { id = Model.Id })
                        </span>
                        <span class="ml-0 mr-2 mb-2">
                            <span class="icon-briefcase mr-2"></span>
                            @Html.ActionLink("Delete", "Delete", "Jobs", new { id = Model.Id })
                        </span>
                    }
                </div>



            </div>
            <div class="col-lg-4">
                <div class="bg-light p-3 border rounded mb-4">
                    <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Job Summary</h3>
                    <ul class="list-unstyled pl-3 mb-0">
                        <li class="mb-2"><strong class="text-black">Published on:</strong>@Model.PostDate.ToLongDateString()</li>
                        <li class="mb-2"><strong class="text-black">Vacancy:</strong> 20</li>
                        <li class="mb-2"><strong class="text-black">Employment Status:</strong>@Model.Type</li>
                        <li class="mb-2"><strong class="text-black">Experience:</strong>@Model.ExperienceYears</li>
                        <li class="mb-2"><strong class="text-black">Job Location:</strong>@Model.Location</li>
                        <li class="mb-2"><strong class="text-black">Salary:</strong>@Model.SalaryRange</li>
                        <li class="mb-2"><strong class="text-black">Gender:</strong> Any</li>
                        <li class="mb-2"><strong class="text-black">Application Deadline:</strong>@Model.ExpiryDate.ToLongDateString()</li>
                    </ul>
                </div>

        
            </div>
        </div>
    </div>
</section>

jobs/Views/Jobs/Index.cshtml
@model IEnumerable<jobs.Models.Job>

@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    <!--  Layout = "~/Views/Shared/_Layout - nosides.cshtml";-->
    Layout = "~/Views/Shared/_Layout - nosides.cshtml";
    ViewData["Title"] = "Job Listings";
}

<section class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="section-title mb-2">@Model.Count() Jobs Listed</h2>
            </div>
        </div>
    </div>
</section>

@if (ViewData["sasa"] != null)
{
    <div class="alert alert-primary" role="alert">
        Your email has been sent, we'll get back to you soon
    </div>
}



<div class="row align-items-center justify-content-center">
    <div class="col-md-12">
        @using (Html.BeginForm("Search", "Jobs", FormMethod.Post, new { @class = "search-jobs-form" }))
        {

            <div class="row mb-5">
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <div class="class=" col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0"">
                        <input class="form-control form-control-lg" placeholder="job title" name="Title">

                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <select name="Province" id="Province" class="form-control form-control-lg">
                        <option value="">Select province</option>
                        <option value="Western Cape">Western Cape</option>
                        <option value="Eastern Cape">Eastern Cape</option>
                        <option value="Northen Cape">Northen Cape</option>
                        <option value="North West">North West</option>
                        <option value="Freestate">Freestate</option>
                        <option value="Kwazulu Natal">Kwazulu Natal</option>
                        <option value="Gauteng">Gauteng</option>
                        <option value="Limpopo">Limpopo</option>
                        <option value="Mpumalanga">Mpumalanga</option>
                    </select>


                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <select name="JobType" id="JobType" class="form-control form-control-lg">
                        <option value="">Select work type</option>
                        <option value="Full time">Full time</option>
                        <option value="Part time">Part Time</option>
                        <option value="Freelance">Freelance</option>
                        <option value="Internship">Internship</option>
                        <option value="Temporary">Temporary</option>
                    </select>
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
            </div>
            <!-- forms closing goes here -->
        }
    </div>
</div>










@foreach (var item in Model)
{
    <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">

        <div class="col-md-4">
            <span class="badge @item.badge px-2 py-1 mb-3">@item.Type</span>
            <h2>
                @Html.ActionLink(item.Title, "Details", "Jobs", new { id = item.Id })

            </h2>
            <p class="meta">Publisher: <strong>@item.businessProfile.Name</strong>
        </div>
        <div class="col-md-4 text-center">
            <h3>@item.Location</h3>

        </div>
        <div class="col-md-4 text-md-right">
            <strong class="text-black">@item.SalaryRange</strong>
        </div>


    </div>
}





@section Scripts
    {
    <script>

        

        $(document).ready(function () {
            $(".alert").fadeTo(3000, 500).slideUp(500, function () {
                $(".alert").slideUp(500);
            });
        });
    </script>
}

jobs/Views/Jobs/PostedJobs.cshtml
@model IEnumerable<jobs.Models.Job>

@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    <!--  Layout = "~/Views/Shared/_Layout - nosides.cshtml";-->
    Layout = "~/Views/Shared/_Layout - nosides.cshtml";
    ViewData["Title"] = "Your posted jobs";
}



@if (ViewBag.jobs)
{

@foreach (var item in Model)
{
    <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">

        <div class="col-md-3">
            <span class="badge @item.badge px-2 py-1 mb-3">@item.Type</span>
            <h2>
                @Html.ActionLink(item.Title, "Details", "Jobs", new { id = item.Id })

            </h2>
            <p class="meta">Publisher: <strong>@item.businessProfile.Name</strong> 
        </div>
        <div class="col-md-3 text-center">
            <h3>@item.Location</h3>

        </div>
        <div class="col-md-3 text-md-right">
            <strong class="text-black">@item.SalaryRange</strong>
        </div>
        
        
        <div class="col-md-3 text-right">
            <a href="@Url.Action("Applied", "Profiles", new { jobId = item.Id })">
                <h3>@item.JobProfiles.Count</h3>
                @if (@item.JobProfiles.Count == 1)
                {
                    <span class="meta">Applicant</span>
                }
                else
                {
                    <span class="meta">Applicants</span>
                }
            </a>
        </div>
       
    </div>
}
}
else
{
<h2>You don't have any posted jobs yet</h2>
}

jobs/Views/Jobs/Search.cshtml
@model IEnumerable<jobs.Models.Job>

@{
    ViewData["Title"] = "Search results";
    Layout = "~/Views/Shared/_Layout - nosides.cshtml";
}


<section class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="section-title mb-2">@Model.Count() Job(s) Listed</h2>
            </div>
        </div>
    </div>
</section>





<div class="row align-items-center justify-content-center">
    <div class="col-md-12">
        @using (Html.BeginForm("Search", "Jobs", FormMethod.Post, new { @class = "search-jobs-form" }))
        {

            <div class="row mb-5">
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <div class="class=" col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0"">
                        <input class="form-control form-control-lg" placeholder="job title" name="Title">

                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <select name="Province" id="Province" class="form-control form-control-lg">
                        <option value="">Select province</option>
                        <option value="Western Cape">Western Cape</option>
                        <option value="Eastern Cape">Eastern Cape</option>
                        <option value="Northen Cape">Northen Cape</option>
                        <option value="North West">North West</option>
                        <option value="Freestate">Freestate</option>
                        <option value="Kwazulu Natal">Kwazulu Natal</option>
                        <option value="Gauteng">Gauteng</option>
                        <option value="Limpopo">Limpopo</option>
                        <option value="Mpumalanga">Mpumalanga</option>
                    </select>


                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <select name="JobType" id="JobType" class="form-control form-control-lg">
                        <option value="">Select work type</option>
                        <option value="Full time">Full time</option>
                        <option value="Part time">Part Time</option>
                        <option value="Freelance">Freelance</option>
                        <option value="Internship">Internship</option>
                        <option value="Temporary">Temporary</option>
                    </select>
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
            </div>
            <!-- forms closing goes here -->
        }
    </div>
</div>


@if (Model.Count() == 0)
{
           <h2>Please use a different search criteria</h2>
}
else
{

@foreach (var item in Model)
{
    <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">

        <div class="col-md-4">
            <span class="badge @item.badge px-2 py-1 mb-3">@item.Type</span>
            <h2>
                @Html.ActionLink(item.Title, "Details", "Jobs", new { id = item.Id })

            </h2>
            <p class="meta">Publisher: <strong>@item.businessProfile.Name</strong>
        </div>
        <div class="col-md-4 text-center">
            <h3>@item.Location</h3>

        </div>
        <div class="col-md-4 text-md-right">
            <strong class="text-black">@item.SalaryRange</strong>
        </div>


    </div>
}


}